"""Alembic environment, async and SQLite-aware.

The URL comes from core.database rather than alembic.ini so there is one source
of truth for which file is the database. render_as_batch is what makes an
autogenerated ALTER work at all: SQLite cannot alter a column, so Alembic has to
rebuild the table instead.
"""

import asyncio

from alembic import command, context
from sqlalchemy import event
from sqlalchemy.ext.asyncio import create_async_engine

from core.database import DATABASE_URL


def _target_metadata():
    """The models' metadata for a command that compares the database with it,
    otherwise None.

    Only `revision --autogenerate` and `check` compare, and the models would be
    most of every boot's `upgrade head`. An upgrade reads only the naming
    convention, which Base keeps at SQLAlchemy's default. The command is known
    only from the command line, so a programmatic autogenerate fails on
    Alembic's missing-MetaData error.
    """
    opts = context.config.cmd_opts
    comparing = getattr(opts, "autogenerate", False) or getattr(opts, "cmd", (None,))[0] is command.check
    if not comparing:
        return None
    from core import nodes  # noqa: F401  registers the node tables on Base.metadata
    from core.users import Base

    return Base.metadata


target_metadata = _target_metadata()


def _run(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_online() -> None:
    # deploy/start.sh runs `alembic upgrade head` on every boot, including
    # restarts where another process may briefly still hold the database file.
    # This engine takes the same lock tolerance as core.users.engine
    # (connect_args timeout + busy_timeout) so a routine restart does not fail
    # fast on transient contention. It deliberately does not take
    # core.users.engine's `PRAGMA foreign_keys=ON`: render_as_batch above means
    # a column-altering migration rebuilds a table by copy, drop and rename,
    # and foreign-key enforcement during that rebuild can break tables that
    # reference the one being rebuilt (Alembic's batch-mode docs warn against
    # it). Nor does it set WAL/synchronous: those are properties of the
    # database file itself, not the connection, so whichever engine connects
    # first (migrations on a fresh database, otherwise the app) sets them once
    # and they persist; a short-lived, single-connection migration run has no
    # durability or concurrency need of its own to justify setting them again.
    engine = create_async_engine(DATABASE_URL, connect_args={"timeout": 30})

    @event.listens_for(engine.sync_engine, "connect")
    def _set_busy_timeout(dbapi_conn, _conn_rec):
        cur = dbapi_conn.cursor()
        cur.execute("PRAGMA busy_timeout=5000")
        cur.close()

    async with engine.connect() as connection:
        await connection.run_sync(_run)
        await connection.commit()
    await engine.dispose()


if context.is_offline_mode():
    # render_as_batch matches the online path in _run() above: SQLite cannot
    # ALTER TABLE, so any future column-altering migration needs the batch
    # rebuild here too, or `alembic upgrade head --sql` would emit SQL SQLite
    # rejects.
    context.configure(url=DATABASE_URL, target_metadata=target_metadata, literal_binds=True, render_as_batch=True)
    with context.begin_transaction():
        context.run_migrations()
else:
    asyncio.run(run_online())
